import * as React from 'react';
import { TOKENS, TOKEN_META, CONTRAST_TARGETS } from '../generated/tokens';
import { CONTRAST_REPORT } from '../generated/contrast';
import type { GrannyTheme } from '../ThemeProvider';

export interface ColorFoundationProps {
  /**
   * Which theme's values to tabulate. Defaults to the working theme.
   * @default "open-day"
   */
  theme?: GrannyTheme;
  /** Show the full measured-contrast table under the swatches. @default true */
  showContrast?: boolean;
}

/**
 * Foundation sheet: semantic colour roles and their measured contrast.
 *
 * Values and ratios are read from the generated token record and the contrast
 * report, so this sheet cannot display a number that was not actually
 * computed by `design-tokens/validate-contrast.mjs`.
 *
 * Every value is proposed. Dark mode is deliberately absent.
 */
export function ColorFoundation({ theme = 'open-day', showContrast = true }: ColorFoundationProps) {
  const roles = Object.entries(TOKENS[theme].semantic).filter(([, t]) => t.type === 'color');
  const pairs = CONTRAST_REPORT.results.filter((r) => r.theme === theme);

  return (
    <div className="ds-sheet">
      <div>
        <div className="ds-sheet-title">Colour roles — {theme}</div>
        <p className="ds-sheet-note">
          <span className="ds-status-proposed">Proposed</span> Token source v{TOKEN_META.version}. Roles carry
          meaning; the hex underneath is a territory value and can change without renaming a role. A role marked
          <em> generated</em> was proposed by this build and is not in the brand document — its contrast was measured,
          never inherited. Dark mode is out of scope for v1.
        </p>
      </div>

      <div className="ds-swatches">
        {roles.map(([name, t]) => {
          const dark = isDark(String(t.value));
          return (
            <div className="ds-swatch" key={name}>
              <div
                className="ds-swatch-chip"
                style={{ background: String(t.value), color: dark ? '#FFFFFF' : '#152522' }}
              >
                {String(t.value)}
              </div>
              <div className="ds-swatch-name">{name}</div>
              <div className="ds-swatch-meta">
                {t.status === 'proposed-new' ? 'generated by this build' : 'from the brand document'}
                {t.role ? ` — ${t.role}` : ''}
              </div>
            </div>
          );
        })}
      </div>

      {showContrast ? (
        <div className="ds-stack-tight">
          <div className="ds-sheet-title">Measured pairs</div>
          <p className="ds-sheet-note">
            Targets: essential text {CONTRAST_TARGETS.essentialText}:1, supporting text{' '}
            {CONTRAST_TARGETS.supportingText}:1, essential boundary or focus {CONTRAST_TARGETS.essentialBoundaryOrFocus}
            :1. sRGB arithmetic on opaque pairs and explicitly flattened composites — not a device or user
            accessibility test.
          </p>
          <div className="ds-scroll-x">
            <table className="ds-spec-table">
              <thead>
                <tr>
                  <th>Where</th>
                  <th>Pair</th>
                  <th>Target</th>
                  <th>Measured</th>
                  <th>Result</th>
                </tr>
              </thead>
              <tbody>
                {pairs.map((p, i) => (
                  <tr key={i}>
                    <td>{p.where}</td>
                    <td>
                      {p.fg} on {p.bg}
                    </td>
                    <td>{p.target}:1</td>
                    <td>{p.ratio}:1</td>
                    <td>{p.advisory ? 'informational' : p.pass ? 'meets target' : 'BELOW TARGET'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      ) : null}
    </div>
  );
}

function isDark(hex: string): boolean {
  const h = hex.replace('#', '');
  const [r, g, b] = [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
  const lin = (c: number) => (c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4));
  return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b) < 0.4;
}
