#!/usr/bin/env node
// Generates the CSS custom properties, the resolved token record and the
// Android mapping table from design-tokens/tokens.json.
//
// The JSON is the single source of truth. Nothing downstream may introduce a
// colour, size, radius or duration that does not originate here.
//
//   node design-tokens/build-tokens.mjs

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadTokens, resolveTheme, themes } from './lib/resolve.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolvePath(here, '..');
const tokensPath = join(here, 'tokens.json');
const tokens = loadTokens(tokensPath);

const cssVar = (name) => '--ds-' + name.replace(/\./g, '-');

/** dp and sp both map 1:1 to CSS px for the web specimen. Review-only. */
const dim = (v) => (typeof v === 'number' ? `${v}px` : v);

/**
 * The dimension and duration primitives are the scale itself, and component
 * styles legitimately reach for a step of it. Colour primitives are
 * deliberately NOT emitted: a colour may only reach a component through a
 * semantic role, which is what keeps raw hex out of component styles.
 */
function scaleBlock() {
  const lines = [];
  for (const [name, def] of Object.entries(tokens.primitive)) {
    if (name.startsWith('$')) continue;
    if (def.type !== 'dimension' && def.type !== 'duration') continue;
    const v = def.type === 'duration' ? `${def.value}ms` : dim(def.value);
    lines.push(`  ${cssVar(name)}: ${v};`);
  }
  return lines;
}

function semanticBlock(resolved, { includeShared }) {
  const lines = [];
  for (const [name, def] of Object.entries(resolved.semantic)) {
    const shared = !tokens.semantic[name].themes; // no per-theme map => theme-independent
    if (shared !== includeShared) continue;
    const v = def.type === 'dimension' ? dim(def.resolved) : def.resolved;
    lines.push(`  ${cssVar(name)}: ${v};`);
  }
  return lines;
}

function componentBlock(resolved) {
  return Object.entries(resolved.component).map(([name, def]) => {
    const v = typeof def.resolved === 'number' ? dim(def.resolved) : def.resolved;
    return `  ${cssVar('cmp.' + name)}: ${v};`;
  });
}

function typographyBlock() {
  const lines = [];
  for (const [role, t] of Object.entries(tokens.typography)) {
    if (role.startsWith('$')) continue;
    // sp scaled by the in-app TextScale on top of whatever the browser/OS
    // already applied to the root font size.
    lines.push(`  ${cssVar('type.' + role + '.size')}: calc(${t.size}px * var(--ds-text-scale, 1));`);
    lines.push(`  ${cssVar('type.' + role + '.line')}: calc(${t.lineHeight}px * var(--ds-text-scale, 1));`);
    lines.push(`  ${cssVar('type.' + role + '.weight')}: ${t.weight};`);
    lines.push(`  ${cssVar('type.' + role + '.family')}: var(${cssVar('font.family.' + t.family)}), var(--ds-font-fallback);`);
  }
  return lines;
}

const [working, challenger] = themes(tokens);
const resolvedByTheme = Object.fromEntries(
  themes(tokens).map((t) => [t, resolveTheme(tokens, t)]),
);

const fallbackStack =
  `system-ui, -apple-system, "Segoe UI", Roboto, "Noto Sans", "Helvetica Neue", Arial, sans-serif`;

const header = `/* GENERATED by design-tokens/build-tokens.mjs — do not edit by hand.
 * Source: design-tokens/tokens.json v${tokens.meta.version} (status: ${tokens.meta.status})
 *
 * EVERY VALUE HERE IS PROPOSED. No palette, typeface, radius or motion value
 * is accepted by Simon. Working theme: ${working}. Challenger: ${challenger}.
 * Dark mode is deliberately absent — see tokens.json meta.darkMode.
 *
 * dp/sp are mapped 1:1 to CSS px for the browser specimen. CSS px is NOT
 * proof of Android dp/sp conformance.
 */
`;

const css = [
  header,
  `:root,`,
  `[data-ds-theme="${working}"] {`,
  `  --ds-font-fallback: ${fallbackStack};`,
  `  --ds-text-scale: 1;`,
  ``,
  `  /* primitive scale: spacing steps and raw durations */`,
  ...scaleBlock(),
  ``,
  `  /* theme-independent dimensions, motion and scale */`,
  ...semanticBlock(resolvedByTheme[working], { includeShared: true }),
  ``,
  `  /* ${working} semantic roles */`,
  ...semanticBlock(resolvedByTheme[working], { includeShared: false }),
  ``,
  `  /* typography */`,
  ...typographyBlock(),
  ``,
  `  /* component references */`,
  ...componentBlock(resolvedByTheme[working]),
  `}`,
  ``,
  `[data-ds-theme="${challenger}"] {`,
  `  /* ${challenger} semantic roles — identical role names, different values */`,
  ...semanticBlock(resolvedByTheme[challenger], { includeShared: false }),
  ``,
  ...componentBlock(resolvedByTheme[challenger]),
  `}`,
  ``,
  `/* Reduced motion replaces every duration with an immediate static state`,
  `   change. It never leaves a control mid-transition. */`,
  `@media (prefers-reduced-motion: reduce) {`,
  `  :root, [data-ds-theme] {`,
  `    ${cssVar('motion.press')}: 0ms;`,
  `    ${cssVar('motion.state')}: 0ms;`,
  `    ${cssVar('motion.panel')}: 0ms;`,
  `  }`,
  `}`,
  ``,
].join('\n');

const cssOut = join(repoRoot, 'design-system', 'src', 'styles', 'tokens.css');
mkdirSync(dirname(cssOut), { recursive: true });
writeFileSync(cssOut, css);

// Resolved record — the machine-readable artefact a reviewer or an Android
// mapping task reads instead of re-deriving aliases.
const record = {
  meta: tokens.meta,
  contrastTargets: tokens.contrastTargets,
  themes: Object.fromEntries(
    Object.entries(resolvedByTheme).map(([t, r]) => [
      t,
      {
        semantic: Object.fromEntries(
          Object.entries(r.semantic).map(([n, d]) => [
            n,
            { value: d.resolved, type: d.type, unit: d.unit ?? null, status: d.status, role: d.role ?? null },
          ]),
        ),
        component: Object.fromEntries(
          Object.entries(r.component).map(([n, d]) => [n, { value: d.resolved, references: d.ref }]),
        ),
      },
    ]),
  ),
  typography: tokens.typography,
  scales: tokens.scales,
};
const buildDir = join(here, 'build');
mkdirSync(buildDir, { recursive: true });
writeFileSync(join(buildDir, 'tokens.resolved.json'), JSON.stringify(record, null, 2) + '\n');

// Android mapping table. Generated, not hand-maintained, so it cannot drift
// from the token source. It is a mapping proposal; no Android code exists.
const androidRows = Object.entries(resolvedByTheme[working].semantic)
  .filter(([, d]) => d.type === 'color')
  .map(([n, d]) => `| \`${n}\` | \`${cssVar(n)}\` | \`${d.resolved}\` | \`${androidName(n)}\` | ${d.status} |`);

function androidName(n) {
  return n.replace(/\./g, '_').replace(/-/g, '_');
}

const androidDoc = `# Android mapping (generated, proposed)

Generated by \`design-tokens/build-tokens.mjs\` from \`tokens.json\` v${tokens.meta.version}.
Theme: \`${working}\`.

**No Android implementation exists.** This table is the name/value mapping a
future Compose or resource task would consume. Generating it does not create,
validate or approve Android resources, and dp/sp conformance is unverified —
the browser specimen measures CSS px.

| Semantic role | CSS custom property | ${working} value | Proposed Android name | Status |
|---|---|---|---|---|
${androidRows.join('\n')}

Dimensions, typography and motion resolve from the same source; see
\`build/tokens.resolved.json\` for the complete record including the challenger theme.
`;
writeFileSync(join(buildDir, 'android-mapping.md'), androidDoc);

// A typed module the foundation sheets import, so the specimens render the
// real token values rather than a hand-copied table that can drift.
const tsOut = join(repoRoot, 'design-system', 'src', 'generated', 'tokens.ts');
mkdirSync(dirname(tsOut), { recursive: true });
writeFileSync(
  tsOut,
  `// GENERATED by design-tokens/build-tokens.mjs — do not edit.\n` +
    `// Source: design-tokens/tokens.json v${tokens.meta.version}\n\n` +
    `export const TOKEN_META = ${JSON.stringify(record.meta, null, 2)} as const;\n\n` +
    `export const CONTRAST_TARGETS = ${JSON.stringify(record.contrastTargets, null, 2)} as const;\n\n` +
    `export const TOKENS = ${JSON.stringify(record.themes, null, 2)} as const;\n\n` +
    `export const TYPOGRAPHY = ${JSON.stringify(record.typography, null, 2)} as const;\n\n` +
    `export const SCALES = ${JSON.stringify(record.scales, null, 2)} as const;\n\n` +
    `export const PRIMITIVES = ${JSON.stringify(
      Object.fromEntries(
        Object.entries(tokens.primitive)
          .filter(([k]) => !k.startsWith('$'))
          .map(([k, v]) => [k, { value: v.value, status: v.status, source: v.source ?? null }]),
      ),
      null,
      2,
    )} as const;\n`,
);

const semCount = Object.keys(resolvedByTheme[working].semantic).length;
const cmpCount = Object.keys(resolvedByTheme[working].component).length;
console.log(`tokens: ${semCount} semantic + ${cmpCount} component references x ${themes(tokens).length} themes`);
console.log(`wrote ${cssOut}`);
console.log(`wrote ${join(buildDir, 'tokens.resolved.json')}`);
console.log(`wrote ${join(buildDir, 'android-mapping.md')}`);
